
#ifndef __DEBICT_EUROBOT_CONTROLLER__EUROBOT_CONTROLLER_COMPILER_H__
#define __DEBICT_EUROBOT_CONTROLLER__EUROBOT_CONTROLLER_COMPILER_H__

#define DEBICT_EUROBOT_CONTROLLER_EXPORT __attribute__((visibility("default")))
#define DEBICT_EUROBOT_CONTROLLER_IMPORT

#define DEBICT_EUROBOT_CONTROLLER_PUBLIC __attribute__((visibility("default")))
#define DEBICT_EUROBOT_CONTROLLER_LOCAL __attribute__((visibility("hidden")))

#define DEBICT_EUROBOT_CONTROLLER_PUBLIC_TYPE

#endif // __DEBICT_EUROBOT_CONTROLLER__EUROBOT_CONTROLLER_COMPILER_H__